import { Brain, Trophy, Link, Check } from 'lucide-react';
import { useReveal } from '../../hooks/useLanding';

const FEATURES = [
  {
    icon:    <Brain size={26} />,
    color:   '#9B81FF',
    bg:      'rgba(124,92,252,0.1)',
    border:  'rgba(124,92,252,0.22)',
    tag:     'AI Engine',
    tagColor:'#9B81FF',
    tagBg:   'rgba(124,92,252,0.12)',
    tagBorder:'rgba(124,92,252,0.25)',
    title:   'Adaptive AI Challenges',
    body:    'Every question is uniquely generated by GPT-4, calibrated in real-time to your level, accuracy history, and chosen domain. No two sessions are ever alike.',
    bullets: ['Difficulty scales with your performance', 'Eight knowledge domains, endless topics', 'Questions get harder as you improve'],
  },
  {
    icon:    <Trophy size={26} />,
    color:   '#FFB84D',
    bg:      'rgba(255,184,77,0.1)',
    border:  'rgba(255,184,77,0.22)',
    tag:     'Competitive',
    tagColor:'#FFB84D',
    tagBg:   'rgba(255,184,77,0.1)',
    tagBorder:'rgba(255,184,77,0.25)',
    title:   'Compete & Dominate',
    body:    'Your rank is a live composite of XP, accuracy, streaks, and boss performance. Six prestige tiers from Bronze to Nexora Elite — the top is yours to claim.',
    bullets: ['Six prestige tiers: Bronze to Nexora Elite', 'Rank score combines XP, accuracy & streaks', 'Boss challenges unlock exclusive rewards'],
  },
  {
    icon:    <Link size={26} />,
    color:   '#00D4FF',
    bg:      'rgba(0,212,255,0.08)',
    border:  'rgba(0,212,255,0.18)',
    tag:     'Web3 Native',
    tagColor:'#33DEFF',
    tagBg:   'rgba(0,212,255,0.1)',
    tagBorder:'rgba(0,212,255,0.22)',
    title:   'On-Chain Identity',
    body:    'Your wallet is your identity. Progress, rank, badges, and RITUAL tokens are stored persistently on-chain — not in an account that can be lost or deleted.',
    bullets: ['No email or password required', 'RITUAL tokens earned through gameplay', 'Spend tokens in the in-game shop'],
  },
];

export default function FeaturesSection() {
  const { ref, visible } = useReveal();

  return (
    <section
      id="features"
      className="py-24 md:py-32 relative"
      style={{ background: 'linear-gradient(180deg, #0B1020 0%, #0D1223 100%)' }}
    >
      {/* Subtle ambient glow */}
      <div
        className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] pointer-events-none"
        style={{ background: 'radial-gradient(ellipse, rgba(124,92,252,0.08) 0%, transparent 70%)', filter: 'blur(40px)' }}
      />

      <div className="relative z-10 max-w-7xl mx-auto px-4 md:px-6">
        <div
          ref={ref}
          className="text-center mb-16 transition-all duration-700"
          style={{ opacity: visible ? 1 : 0, transform: visible ? 'translateY(0)' : 'translateY(24px)' }}
        >
          <div
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-4 text-xs font-title font-semibold tracking-widest uppercase"
            style={{ background: 'rgba(124,92,252,0.1)', border: '1px solid rgba(124,92,252,0.25)', color: '#9B81FF' }}
          >
            <Brain size={11} /> Core Features
          </div>
          <h2
            className="font-title font-extrabold mb-4"
            style={{ fontSize: 'clamp(1.8rem, 4vw, 3rem)', letterSpacing: '-0.03em', color: '#E6EDF7' }}
          >
            Built Different. Built to Last.
          </h2>
          <p className="text-lg max-w-xl mx-auto" style={{ color: 'rgba(230,237,247,0.5)' }}>
            Nexora combines adaptive AI, competitive ranking, and Web3 identity into one seamless knowledge arena.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          {FEATURES.map((feat, i) => (
            <FeatureCard key={feat.title} feat={feat} delay={i * 120} />
          ))}
        </div>
      </div>
    </section>
  );
}

function FeatureCard({ feat, delay }: { feat: typeof FEATURES[number]; delay: number }) {
  const { ref, visible } = useReveal();

  return (
    <div
      ref={ref}
      className="p-6 flex flex-col gap-5 transition-all duration-700 rounded-2xl group"
      style={{
        background:      'linear-gradient(145deg, rgba(28,38,64,0.9) 0%, rgba(20,27,45,0.95) 100%)',
        border:          `1px solid ${feat.border}`,
        boxShadow:       '0 4px 20px rgba(0,0,0,0.4)',
        opacity:         visible ? 1 : 0,
        transform:       visible ? 'translateY(0)' : 'translateY(32px)',
        transitionDelay: `${delay}ms`,
      }}
    >
      <div className="flex items-center justify-between">
        <div
          className="w-12 h-12 rounded-xl flex items-center justify-center transition-all duration-300 group-hover:scale-110"
          style={{ background: feat.bg, border: `1px solid ${feat.border}`, color: feat.color }}
        >
          {feat.icon}
        </div>
        <span
          className="text-xs font-title font-bold uppercase tracking-wider px-3 py-1 rounded-full"
          style={{ background: feat.tagBg, border: `1px solid ${feat.tagBorder}`, color: feat.tagColor }}
        >
          {feat.tag}
        </span>
      </div>
      <div>
        <h3 className="font-title font-bold text-xl mb-2" style={{ color: '#E6EDF7' }}>{feat.title}</h3>
        <p className="text-sm leading-relaxed" style={{ color: 'rgba(230,237,247,0.5)' }}>{feat.body}</p>
      </div>
      <ul className="space-y-2 mt-auto">
        {feat.bullets.map(b => (
          <li key={b} className="flex items-start gap-2.5">
            <Check size={13} style={{ color: feat.color, flexShrink: 0, marginTop: 2 }} />
            <span className="text-sm" style={{ color: 'rgba(230,237,247,0.55)' }}>{b}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
